server:
  port: 8003
#mybatis的配置
mybatis:
  type-aliases-package: com.zjy.springcloud.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 333
    username: root
#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8003
    prefer-ip-address: true

#info配置
info:
  app.name: zjy_springcloud
  company.name: golo.com
